export const USER_TYPE_COUNTER = 'counter::user'
export const USER_TYPE = 'user'
export const USER_TYPE_KEY_PREFIX = 'user::'
export const ACCOUNT_TYPE_COUNTER = 'counter::account'
export const ACCOUNT_TYPE = 'account'
export const ACCOUNT_TYPE_KEY_PREFIX = 'account::'